/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package motorbike_rental_system;

import com.mongodb.*;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import static motorbike_rental_system.Login.c;

public class F_Login extends javax.swing.JFrame {

     DBCollection table;
    DB db;
    public F_Login() {
        initComponents();
        showDate();
        showTime();
        try {
            // TODO add your handling code here:
            MongoClient mongo = new MongoClient("localhost", 27017);
            db = mongo.getDB("admin");
            table = db.getCollection("userlogin");
           
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        tx_Date.setText(s.format(d));
        
        
    }
    
    void showTime(){
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                tx_time.setText(s.format(d));
            }
            
        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tx_pass = new javax.swing.JPasswordField();
        bt_login = new keeptoo.KButton();
        tx_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tx_Date = new javax.swing.JLabel();
        tx_time = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_pass.setBackground(new java.awt.Color(204, 204, 204));
        tx_pass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tx_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tx_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_passActionPerformed(evt);
            }
        });
        getContentPane().add(tx_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 250, -1));

        bt_login.setBackground(new java.awt.Color(255, 102, 51));
        bt_login.setForeground(new java.awt.Color(255, 102, 51));
        bt_login.setText("เข้าสู่ระบบ");
        bt_login.setFont(new java.awt.Font("TH Sarabun New", 0, 36)); // NOI18N
        bt_login.setkEndColor(new java.awt.Color(255, 102, 51));
        bt_login.setkHoverEndColor(new java.awt.Color(255, 102, 51));
        bt_login.setkHoverForeGround(new java.awt.Color(255, 102, 51));
        bt_login.setkHoverStartColor(new java.awt.Color(255, 102, 51));
        bt_login.setkSelectedColor(new java.awt.Color(255, 102, 51));
        bt_login.setkStartColor(new java.awt.Color(255, 102, 51));
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 130, -1));

        tx_id.setBackground(new java.awt.Color(204, 204, 204));
        tx_id.setFont(new java.awt.Font("TH Sarabun New", 0, 24)); // NOI18N
        tx_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tx_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tx_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_idActionPerformed(evt);
            }
        });
        getContentPane().add(tx_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 250, -1));

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("รหัสผ่าน:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("ชื่อผู้ใช้งาน:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("ระบบจัดการ Rental Cars ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ef4ff184-2711-4db6-bb8f-7c76ef648a19.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 170));

        tx_Date.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        tx_Date.setForeground(new java.awt.Color(255, 102, 51));
        tx_Date.setText("dd-MM-yyyy");
        getContentPane().add(tx_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        tx_time.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        tx_time.setForeground(new java.awt.Color(255, 102, 51));
        tx_time.setText("HH:MM:SS A");
        getContentPane().add(tx_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ggg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 700, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tx_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        try {
            BasicDBObject whereQuery = new BasicDBObject();
            whereQuery.put("ID", tx_id.getText());
            whereQuery.put("PASS", tx_pass.getText());
            whereQuery.put("level", "Admin");
            DBCursor cursor = table.find(whereQuery);
            
            BasicDBObject whereQuery2 = new BasicDBObject();
            whereQuery2.put("ID", tx_id.getText());
            whereQuery2.put("PASS", tx_pass.getText());
            whereQuery2.put("level", "Employee");
            DBCursor cursor2 = table.find(whereQuery2);
            
            boolean login = false;
            boolean ck = false;
            while(cursor.hasNext()) {
               c =true;
               JLabel text = new JLabel("ยินดีต้อนรับแอดมินเข้าสู่ระบบ!");
               text.setFont(new Font("TH Sarabun New", Font.BOLD, 18));               
               JOptionPane.showMessageDialog(this, text);
               new F_Home_Admin().show();
              
               dispose();
               ck = true;
               login = true;
               
               break;
            }
            if(!login){
               c =false;
               while(cursor2.hasNext()) {
               JLabel text = new JLabel("ยินดีต้อนรับพนักงานเข้าสู่ระบบ!");
               text.setFont(new Font("TH Sarabun New", Font.BOLD, 18));               
               JOptionPane.showMessageDialog(this, text);
               new F_Home_Employee().show();
               dispose();
               ck = true;
               
               break;
            }
            }          
            if(ck==false){
                JLabel text = new JLabel("ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง!");
               text.setFont(new Font("TH Sarabun New", Font.BOLD, 18));               
               JOptionPane.showMessageDialog(this, text);
                tx_id.setText("");
                tx_pass.setText("");
            }
            
            //JOptionPane.showMessageDialog(this, "Login is failed!");
		
            
        } catch (Exception e) {
            
        }   
        
    }//GEN-LAST:event_bt_loginActionPerformed

    private void tx_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_passActionPerformed
    static boolean c ; //เอาไว้เช็คว่าคนที่ล็อคอินเข้ามาเป็นแอดมินหรือพนักงานปกติ
    Boolean getc(){
        return c;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton bt_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tx_Date;
    private javax.swing.JTextField tx_id;
    private javax.swing.JPasswordField tx_pass;
    private javax.swing.JLabel tx_time;
    // End of variables declaration//GEN-END:variables
}
